# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: sparkplug
dist: dist_tools/
before:
  hooks:
    - cd tools/spdevice && go mod tidy
    - cd tools/spmon && go mod tidy

builds:
  - id: spdevice
    dir: tools/spdevice
    main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

  - id: spmon
    dir: tools/spmon
    main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

archives:
  - ids:
    - spmon
    - spdevice
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  # note that this is an array of nfpm configs
  -
    id: spdevice
    ids:
      - spdevice
    release: "1"
    maintainer: thin-edge.io <info@thin-edge.io>
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
      - apk
      - rpm
    package_name: spdevice

  -
    id: spmon
    ids:
      - spmon
    release: "1"
    maintainer: thin-edge.io <info@thin-edge.io>
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
      - apk
      - rpm
    package_name: spmon
